version: 1
update_configs:
  # Update package.json (& lockfiles) monthly
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
  
  - package_manager: "docker"
    directory: "/"
    update_schedule: "monthly"
