version: 1
update_configs:
  # Update package.json (& lockfiles) monthly
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"

    # Apply default label to created pull requests
    default_labels:
      - "dependabot"
